version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8085:80"
    volumes:
      - ../material/wood:/usr/share/nginx/html
      - ./nginx-conf.conf:/etc/nginx/conf.d/default.conf:ro
